CROSS_COMPILE = /work/cortex-A8/buildroot/output/host/usr/bin/arm-buildroot-linux-gnueabihf-
BR_CCACHE = 
BR_COMPILER_CFLAGS = -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os
BR_COMPILER_CXXFLAGS = -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os
EGLFS_PLATFORM_HOOKS_SOURCES = 
GCC_MACHINE_DUMP = arm-buildroot-linux-gnueabihf
